name: Deploy to Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Install and Build Backend
        #  Build backend
        run: |
          cd backend/
          touch .env
          echo ${{ secrets.BACK_ENV_FILE}} > .env
          npm ci
          NODE_ENV=production npm run build

      - name: Download backend project as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: ./build

      - name: Install and Build Frontend
        #  Build frontend
        run: |
          cd ../frontend/
          touch .env
          echo ${{ secrets.FRONT_ENV_FILE}} > .env
          npm ci
          NODE_ENV=production npm run build

      - name: Download frontend project as artifact
        uses: actions/upload-artifact@master
        with:
          name: frontend
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@master
        with:
          name: backend
          path: .
      - name: Download frontend artifact
        uses: actions/download-artifact@master
        with:
          name: frontend
          path: .

      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: .*
          TARGET: "~/www/lesceramiquesdemanette"
