name: Deploy to Oracle Cloud

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Install and Build Backend
        #  Build backend
        run: |
          cd backend/
          touch .env
          echo ${{ secrets.BACK_ENV_FILE}} > .env
          npm ci
          NODE_ENV=production npm run build
          mv build ../backend_
          cd .. && rm -rf backend/ && mv backend_ backend

      - name: Install and Build Frontend
        #  Build frontend
        run: |
          cd frontend/
          touch .env
          echo ${{ secrets.FRONT_ENV_FILE}} > .env

          npm i

          npm run build
          mv build package.json node_modules ../frontend_
          cd .. && rm -rf frontend/ && mv frontend_ frontend

      - name: Upload frontend and backend projects as artifact
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            ./frontend/
            ./backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download builds artifact
        uses: actions/download-artifact@master
        with:
          name: builds
          path: ./${{ github.event.repository.name }}

      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "~/www/"
